### ISSUE TITLE
create versions without stage-0..3 presets

### ISSUE THREAD

**Issue by graingert** [michaelcontento/babel-preset-modern-node#37]
Hey it would be great to enable this package on a few of my server side projects, but I don't want to enable transpiling stage-0..3 features until they're in an official ES

**Comment by graingert** [comment]
also it seems that this is missing the `do .. while` transform-do-expressions

**Comment by michaelcontento** [comment]
> Hey it would be great to enable this package on a few of my server side projects, but I don't want to enable transpiling stage-0..3 features until they're in an official ES

Please have a look at PR #43 and leave your opinion about this solution, thanks a lot :)

**Comment by graingert** [comment]
I think if you removed stage-0...3 people can just use presets:
[modern-node, stage-0]

**Comment by michaelcontento** [comment]
Uhm .. yes .. this was simply too obvious 😂

**Comment by michaelcontento** [comment]
Have you looked at https://github.com/rtsao/babel-preset-es2015-node? Maybe I should simply add a notice at the top of the README pointing over to this preset?

**Comment by graingert** [comment]
No their preset doesn't work
https://github.com/rtsao/babel-preset-es2015-node/blob/node6/index.js

**Comment by graingert** [comment]
They have no tests etc

**Comment by calebmer** [comment]
I also prefer this package's versioning scheme. It isn't tied to another technology's versioning.
