### ISSUE TITLE
Add decorator support

### ISSUE THREAD

**Issue by abhisekp** [michaelcontento/babel-preset-modern-node#47]
[![babel-plugin-transform-decorators-legacy](https://img.shields.io/badge/NPM_Package:-babel--plugin--transform--decorators--legacy-c12127.svg?style=flat-square&maxAge=2592000)](https://www.npmjs.com/package/babel-plugin-transform-decorators-legacy)

**Comment by baldore** [comment]
I think decorators should not be here, considering that the specification is still in progress.

**Comment by abhisekp** [comment]
I think all latest and greatest should be here as this is not official. If anyone don't want to use decorators, then they may not. :)

**Comment by michaelcontento** [comment]
[transform-decorators](https://babeljs.io/docs/plugins/transform-decorators/) has been [disabled from stage-1](https://babeljs.io/docs/plugins/preset-stage-1/) and thus is far from being stable. 

Yes, this preset is not official. But the intention of this is the support all *stable* features for a wide range of node versions (with as less transforms as possible). 

If you want to use unstable transforms in addition to this, simple add them to your config like `  "presets": ["modern-node/6.0", "stage-0"]`

**Comment by abhisekp** [comment]
Yep! doing just that :+1: 
Thank you. :smiley:
