### ISSUE TITLE
document es2016 support

### ISSUE THREAD

**Issue by graingert** [michaelcontento/babel-preset-modern-node#52]

**Comment by michaelcontento** [comment]
Should already be support or do you know what I've missed?

**Comment by graingert** [comment]
@michaelcontento ah it looks like it is supported. It would be nice to document it. [babel-preset-modern-browsers](https://www.npmjs.com/package/babel-preset-modern-browsers) have a nice little [compat-table](https://www.npmjs.com/package/babel-preset-modern-browsers#compatibility-table) with [ES2015](https://www.npmjs.com/package/babel-preset-modern-browsers#es2015) and   [ES2016](https://www.npmjs.com/package/babel-preset-modern-browsers#es2016)

**Comment by michaelcontento** [comment]
I don't have the time to compose a full compat-table like `babel-preset-modern-browsers` - but **(!)** I've added some notes to the `README.md`. Feel free to contribute to these 😄
