### ISSUE TITLE
super(...arguments) fails on node 4.4.3

### ISSUE THREAD

**Issue by sheerun** [michaelcontento/babel-preset-modern-node#59]
It seems some plugin/preset is missing, as I get following error when switching from es2015:

```
      super(...arguments);
            ^^^

SyntaxError: Unexpected token ...
```

**Comment by sheerun** [comment]
es2015-node4 works as expected

**Comment by michaelcontento** [comment]
Can you provide me with a testcase? I'm unable to reproduce this error 😢

**Comment by michaelcontento** [comment]
This module has been deprecated in favor of [babel-preset-env](https://github.com/babel/babel-preset-env).

But thank you for using this package! Have a nice day 😃
